languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon CloudOps Linux Workshop"
theme = "learn"
uglyurls = true
# googleAnalytics = "UA-44634850-2"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "John Dixon"
description = "Amazon CloudOps Linux Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
editURL = "https://github.com/dixonaws/aws-cloudops-linux/edit/main/content/"

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @dixonjp90"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=dixonjp90"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> John Dixon"
identifier = "li0"
url = "https://www.linkedin.com/in/jpd44/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Claudiu Bota"
identifier = "li1"
url = "https://www.linkedin.com/in/claudiu-bota-6b400315a/"
weight = 2



[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
